/*
 *   This file was generated by a tool.
 *   Do not edit it, otherwise the changes will be overwritten.
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using F8Framework.Core;
using UnityEngine.Scripting;

namespace F8Framework.Tests
{
	internal class DemoF8DataManager : ModuleSingleton<DemoF8DataManager>, IModule
	{
		public string VariantName { get; set; }
		private AssetLoadTracker _assetLoadTracker;
		private AssetLoadTracker AssetLoadTracker => _assetLoadTracker ??= new AssetLoadTracker();
		private DemoSheet1 p_Sheet1;
		private DemoSheet2 p_Sheet2;
		private DemoLocalizedStrings p_LocalizedStrings;

		[Preserve]
		public DemoSheet1Item GetSheet1ByID(System.Int32 id)
		{
			DemoSheet1Item t = null;
			p_Sheet1.Dict.TryGetValue(id, out t);
			if (t == null) LogF8.LogError("找不到id： " + id + " ，配置表： Sheet1");
			return t;
		}

		[Preserve]
		public Dictionary<System.Int32, DemoSheet1Item> GetSheet1()
		{
			return p_Sheet1.Dict;
		}

		[Preserve]
		public DemoSheet2Item GetSheet2ByID(System.Int32 id)
		{
			DemoSheet2Item t = null;
			p_Sheet2.Dict.TryGetValue(id, out t);
			if (t == null) LogF8.LogError("找不到id： " + id + " ，配置表： Sheet2");
			return t;
		}

		[Preserve]
		public Dictionary<System.Int32, DemoSheet2Item> GetSheet2()
		{
			return p_Sheet2.Dict;
		}

		[Preserve]
		public DemoLocalizedStringsItem GetLocalizedStringsByID(System.Int32 id)
		{
			DemoLocalizedStringsItem t = null;
			p_LocalizedStrings.Dict.TryGetValue(id, out t);
			if (t == null) LogF8.LogError("找不到id： " + id + " ，配置表： LocalizedStrings");
			return t;
		}

		[Preserve]
		public Dictionary<System.Int32, DemoLocalizedStringsItem> GetLocalizedStrings()
		{
			return p_LocalizedStrings.Dict;
		}

		[Preserve]
		public void LoadLocalizedStrings()
		{
			p_LocalizedStrings = Load<DemoLocalizedStrings>("LocalizedStrings") as DemoLocalizedStrings;
		}

		[Preserve]
		public void LoadLocalizedStringsCallback(Action onLoadComplete)
		{
			Util.Unity.StartCoroutine(LoadLocalizedStringsIEnumerator(onLoadComplete));
		}

		[Preserve]
		public IEnumerator LoadLocalizedStringsIEnumerator(Action onLoadComplete = null)
		{
			yield return LoadAsync<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
			onLoadComplete?.Invoke();
		}

		[Preserve]
		public void LoadAll()
		{
			p_Sheet1 = Load<DemoSheet1>("Sheet1") as DemoSheet1;
			p_Sheet2 = Load<DemoSheet2>("Sheet2") as DemoSheet2;
			p_LocalizedStrings = Load<DemoLocalizedStrings>("LocalizedStrings") as DemoLocalizedStrings;
		}

		[Preserve]
		public void RuntimeLoadAll(Dictionary<String, System.Object> objs = null)
		{
			if (objs == null)
			{
				objs = new Dictionary<string, object>();
				ReadExcel.Instance.LoadAllExcelData(objs);
			}
			p_Sheet1 = objs["Sheet1"] as DemoSheet1;
			p_Sheet2 = objs["Sheet2"] as DemoSheet2;
			p_LocalizedStrings = objs["LocalizedStrings"] as DemoLocalizedStrings;
		}

		[Preserve]
		public IEnumerable LoadAllAsync()
		{
			yield return LoadAsync<DemoSheet1>("Sheet1", result => p_Sheet1 = result as DemoSheet1);
			yield return LoadAsync<DemoSheet2>("Sheet2", result => p_Sheet2 = result as DemoSheet2);
			yield return LoadAsync<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
#if UNITY_EDITOR
			if (AssetManager.Instance.IsEditorMode)
			{
				RuntimeLoadAll();
			}
#endif
		}

		[Preserve]
		public async Task LoadAllAsyncTask()
		{
			await LoadAsyncTask<DemoSheet1>("Sheet1", result => p_Sheet1 = result as DemoSheet1);
			await LoadAsyncTask<DemoSheet2>("Sheet2", result => p_Sheet2 = result as DemoSheet2);
			await LoadAsyncTask<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
#if UNITY_EDITOR
			if (AssetManager.Instance.IsEditorMode)
			{
				RuntimeLoadAll();
			}
#endif
		}

		[Preserve]
		public void LoadAllAsyncCallback(Action onLoadComplete = null)
		{
			Util.Unity.StartCoroutine(LoadAllAsyncIEnumerator(onLoadComplete));
		}

		[Preserve]
		public IEnumerator LoadAllAsyncIEnumerator(Action onLoadComplete = null)
		{
			yield return LoadAsync<DemoSheet1>("Sheet1", result => p_Sheet1 = result as DemoSheet1);
			yield return LoadAsync<DemoSheet2>("Sheet2", result => p_Sheet2 = result as DemoSheet2);
			yield return LoadAsync<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
#if UNITY_EDITOR
			if (AssetManager.Instance.IsEditorMode)
			{
				RuntimeLoadAll();
			}
#endif
			onLoadComplete?.Invoke();
		}

		[Preserve]
		public T Load<T>(string name)
		{
			TextAsset textAsset = AssetLoadTracker.Load<TextAsset>(name);
			if (textAsset == null)
			{
				return default(T);
			}
			UnloadAsset(name, false);
			T obj = Util.BinarySerializer.Deserialize<T>(textAsset.bytes);
			return obj;
		}

		[Preserve]
		public IEnumerator LoadAsync<T>(string name, Action<T> callback)
		{
			TextAsset textAsset = null;
			yield return AssetLoadTracker.LoadAsync<TextAsset>(name, result => textAsset = result);
			if (textAsset != null)
			{
				UnloadAsset(name, false);
				T obj = Util.BinarySerializer.Deserialize<T>(textAsset.bytes);
				callback?.Invoke(obj);
			}
		}

		[Preserve]
		public async Task LoadAsyncTask<T>(string name, Action<T> callback)
		{
			TextAsset textAsset = null;
			BaseLoader load = AssetLoadTracker.LoadAsync<TextAsset>(name, result => textAsset = result);
			await load;
			if (textAsset != null)
			{
				UnloadAsset(name, false);
				T obj = Util.BinarySerializer.Deserialize<T>(textAsset.bytes);
				callback?.Invoke(obj);
			}
		}

		public void UnloadAsset(string name, bool unloadAllLoadedObjects = false)
		{
			_assetLoadTracker?.Release(name, unloadAllLoadedObjects);
		}

		public void ClearAssetLoadTracker(bool unloadAllLoadedObjects = false)
		{
			if (_assetLoadTracker == null)
				return;

			_assetLoadTracker.ReleaseAll(unloadAllLoadedObjects);
			_assetLoadTracker = null;
		}

		public void OnInit(object createParam)
		{
			
		}

		public void OnUpdate()
		{
			
		}

		public void OnLateUpdate()
		{
			
		}

		public void OnFixedUpdate()
		{
			
		}

		public void OnTermination()
		{
			ClearAssetLoadTracker(true);
			p_Sheet1 = null;
			p_Sheet2 = null;
			p_LocalizedStrings = null;
			VariantName = null;
			base.Destroy();
		}
	}
}
