/*
 *   This file was generated by a tool.
 *   Do not edit it, otherwise the changes will be overwritten.
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using F8Framework.Core;
using UnityEngine.Scripting;

namespace F8Framework.Tests
{
	internal class DemoF8DataManager : ModuleSingleton<DemoF8DataManager>, IModule
	{
		private DemoSheet1 p_Sheet1;
		private DemoSheet2 p_Sheet2;
		private DemoLocalizedStrings p_LocalizedStrings;

		[Preserve]
		public DemoSheet1Item GetSheet1ByID(System.Int32 id)
		{
			DemoSheet1Item t = null;
			p_Sheet1.Dict.TryGetValue(id, out t);
			if (t == null) LogF8.LogError("找不到id： " + id + " ，配置表： Sheet1");
			return t;
		}

		[Preserve]
		public Dictionary<System.Int32, DemoSheet1Item> GetSheet1()
		{
			return p_Sheet1.Dict;
		}

		[Preserve]
		public DemoSheet2Item GetSheet2ByID(System.Int32 id)
		{
			DemoSheet2Item t = null;
			p_Sheet2.Dict.TryGetValue(id, out t);
			if (t == null) LogF8.LogError("找不到id： " + id + " ，配置表： Sheet2");
			return t;
		}

		[Preserve]
		public Dictionary<System.Int32, DemoSheet2Item> GetSheet2()
		{
			return p_Sheet2.Dict;
		}

		[Preserve]
		public DemoLocalizedStringsItem GetLocalizedStringsByID(System.Int32 id)
		{
			DemoLocalizedStringsItem t = null;
			p_LocalizedStrings.Dict.TryGetValue(id, out t);
			if (t == null) LogF8.LogError("找不到id： " + id + " ，配置表： LocalizedStrings");
			return t;
		}

		[Preserve]
		public Dictionary<System.Int32, DemoLocalizedStringsItem> GetLocalizedStrings()
		{
			return p_LocalizedStrings.Dict;
		}

		[Preserve]
		public void LoadLocalizedStrings()
		{
			p_LocalizedStrings = Load<DemoLocalizedStrings>("LocalizedStrings") as DemoLocalizedStrings;
		}

		[Preserve]
		public void LoadLocalizedStringsCallback(Action onLoadComplete)
		{
			Util.Unity.StartCoroutine(LoadLocalizedStringsIEnumerator(onLoadComplete));
		}

		[Preserve]
		public IEnumerator LoadLocalizedStringsIEnumerator(Action onLoadComplete = null)
		{
			yield return LoadAsync<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
			onLoadComplete?.Invoke();
		}

		[Preserve]
		public void LoadAll()
		{
			p_Sheet1 = Load<DemoSheet1>("Sheet1") as DemoSheet1;
			p_Sheet2 = Load<DemoSheet2>("Sheet2") as DemoSheet2;
			p_LocalizedStrings = Load<DemoLocalizedStrings>("LocalizedStrings") as DemoLocalizedStrings;
		}

		[Preserve]
		public void RuntimeLoadAll(Dictionary<String, System.Object> objs)
		{
			p_Sheet1 = objs["Sheet1"] as DemoSheet1;
			p_Sheet2 = objs["Sheet2"] as DemoSheet2;
			p_LocalizedStrings = objs["LocalizedStrings"] as DemoLocalizedStrings;
		}

		[Preserve]
		public IEnumerable LoadAllAsync()
		{
			yield return LoadAsync<DemoSheet1>("Sheet1", result => p_Sheet1 = result as DemoSheet1);
			yield return LoadAsync<DemoSheet2>("Sheet2", result => p_Sheet2 = result as DemoSheet2);
			yield return LoadAsync<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
#if UNITY_EDITOR
			if (AssetManager.Instance.IsEditorMode)
			{
				ReadExcel.Instance.LoadAllExcelData();
			}
#endif
		}

		[Preserve]
		public async Task LoadAllAsyncTask()
		{
			await LoadAsyncTask<DemoSheet1>("Sheet1", result => p_Sheet1 = result as DemoSheet1);
			await LoadAsyncTask<DemoSheet2>("Sheet2", result => p_Sheet2 = result as DemoSheet2);
			await LoadAsyncTask<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
#if UNITY_EDITOR
			if (AssetManager.Instance.IsEditorMode)
			{
				ReadExcel.Instance.LoadAllExcelData();
			}
#endif
		}

		[Preserve]
		public void LoadAllAsyncCallback(Action onLoadComplete = null)
		{
			Util.Unity.StartCoroutine(LoadAllAsyncIEnumerator(onLoadComplete));
		}

		[Preserve]
		public IEnumerator LoadAllAsyncIEnumerator(Action onLoadComplete = null)
		{
			yield return LoadAsync<DemoSheet1>("Sheet1", result => p_Sheet1 = result as DemoSheet1);
			yield return LoadAsync<DemoSheet2>("Sheet2", result => p_Sheet2 = result as DemoSheet2);
			yield return LoadAsync<DemoLocalizedStrings>("LocalizedStrings", result => p_LocalizedStrings = result as DemoLocalizedStrings);
#if UNITY_EDITOR
			if (AssetManager.Instance.IsEditorMode)
			{
				ReadExcel.Instance.LoadAllExcelData();
			}
#endif
			onLoadComplete?.Invoke();
		}

		[Preserve]
		public T Load<T>(string name)
		{
			TextAsset textAsset = AssetManager.Instance.Load<TextAsset>(name);
			if (textAsset == null)
			{
				return default(T);
			}
			AssetManager.Instance.Unload(name, false);
			T obj = Util.LitJson.ToObject<T>(textAsset.text);
			return obj;
		}

		[Preserve]
		public IEnumerator LoadAsync<T>(string name, Action<T> callback)
		{
			var load = AssetManager.Instance.LoadAsyncCoroutine<TextAsset>(name);
			yield return load;
			TextAsset textAsset = AssetManager.Instance.GetAssetObject<TextAsset>(name);
			if (textAsset != null)
			{
				AssetManager.Instance.Unload(name, false);
				T obj = Util.LitJson.ToObject<T>(textAsset.text);
				callback(obj);
			}
		}

		[Preserve]
		public async Task LoadAsyncTask<T>(string name, Action<T> callback)
		{
			BaseLoader load = AssetManager.Instance.LoadAsync<TextAsset>(name);
			await load;
			TextAsset textAsset = AssetManager.Instance.GetAssetObject<TextAsset>(name);
			if (textAsset != null)
			{
				AssetManager.Instance.Unload(name, false);
				T obj = Util.LitJson.ToObject<T>(textAsset.text);
				callback(obj);
			}
		}

		public void OnInit(object createParam)
		{
			
		}

		public void OnUpdate()
		{
			
		}

		public void OnLateUpdate()
		{
			
		}

		public void OnFixedUpdate()
		{
			
		}

		public void OnTermination()
		{
			base.Destroy();
		}
	}
}
